blog/urls.py
from django.urls import path

from .views import PostDetailView, PostListView, PostShareView

app_name = 'blog'
urlpatterns = [
    path('', PostListView, name='posts_list'),
    path('<slug:tag_slug>/', PostListView, name='posts_list_by_tag'),
    path('<int:pk>/detail/', PostDetailView, name='post_detail'),
    path('<int:pk>/share/', PostShareView, name='post_share'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('blog/', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.


class Post(models.Model):

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='blog_posts',
    )
    body = models.TextField()

    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,
                              default='draft',)
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})


class Comment(models.Model):

    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')

    name = models.CharField(max_length=25)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return "Comment by {} on {}".format(self.name, self.post)

blog/forms.py
from django import forms

from .models import Comment


class PostShareForm(forms.Form):

    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['name', 'email', 'body', ]

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, CreateView, DetailView
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.db.models import Count

from .models import Post, Comment
from .forms import PostShareForm, CommentForm
from taggit.models import Tag

# Create your views here.


def PostShareView(request, pk):
    post = get_object_or_404(Post, pk=pk)
    sent = False

    if request.method == 'POST':
        form = PostShareForm(request.POST)
        if form.is_valid() == True:
            cd = form.cleaned_data
            # send email
            post_url = request.build_absolute_uri(post.get_absolute_url())

            subject = "{} ({}) recommend you to read {}".format(
                cd['name'],
                cd['email'], post.title)

            message = "Read {} at {} \n\n\{}'s comments:{}".format(
                post.title, post_url, cd['name'], cd['comments'])

            send_mail(subject, message, 'salezarop@gmail.com', [cd['to']])
            sent = True
    else:
        form = PostShareForm()

    context = {
        'post': post,
        'form': form,
        'sent': sent,
    }
    return render(request, 'post_share.html', context)


def PostListView(request, tag_slug=None):
    tag = None

    if request.method == 'POST':
        tag_slug = request.POST['tag_slug']
        url = "%s/" % (tag_slug)
        return HttpResponseRedirect(url)
    elif tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts_list = Post.objects.filter(tags__in=[tag])
    else:
        posts_list = Post.objects.all()

    paginator = Paginator(posts_list, 4)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    context = {
        'posts': posts,
        'tag': tag,
    }

    return render(request, 'posts_list.html', context)


def PostDetailView(request, pk):
    post = get_object_or_404(Post, id=pk)
    comments = post.comments.filter(active=True)
    new_comment = None

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(tags__in=post_tags_ids)\
                                .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
        .order_by('-same_tags', '-publish')[:4]

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            comment_form = CommentForm()
    else:
        comment_form = CommentForm()

    context = {
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form,
        'similar_posts': similar_posts,
    }
    return render(request, 'post_detail.html', context)


# class PostListView(ListView):
#     model = Post
#     template_name = "posts_list.html"
#     context_object_name = "posts"
#     paginate_by = 4


# class PostDetailView(DetailView):
#     model = Post
#     template_name = "post_detail.html"

templates/base.html
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>


    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>

<body>
    <div id="navbar" class="">
        <nav class="container-fluid">
            <div class="" style="min-height: 10px;">

            </div>
            <div style="border-bottom: 1px solid #21b7d1;">
                <nav id="navbar" class="navbar navbar-expand-lg navbar-light bg-light" style=" border-radius: 0.4em;">
                    <button class="navbar-brand btn btn-light font-weight-bold" style="color: #1c9cb3"
                        disabled>Blogger</button>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'blog:posts_list' %}">Posts
                                    <span class="sr-only">(current)</span></a>
                            </li>
                            <!-- <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li> -->

                        </ul>
                        {% block searchform %}
                        {% endblock searchform %}
                    </div>
                </nav>
            </div>
        </nav>
    </div>

    <div id="main" class="container">

        {% block content %}
        {% endblock content %}

    </div>


    <!-- Footer -->
    <footer id="footer" class="conptainer-fluid">

        <div class="row">
            <hr class="col" style="border-top: 2px solid #1c9cb3; width: auto;">
        </div>

        <div class="container text-center text-md-left mt-5">

            <div class="row mt-3 text-muted">

                <div class="col-md-3 col-lg-4 col-xl-3 mb-4">

                    <h6 class="text-uppercase font-weight-bold">Blogger</h6>
                    <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
                    <p>Here you can get use of our knowledge and experience form working for years
                        and apply it to your job easily.
                    </p>

                </div>

                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

                    <h6 class="text-uppercase font-weight-bold">Posts Type</h6>
                    <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
                    <p>
                        <a class="text-muted" href="#!">Computer Science</a>
                    </p>
                    <p>
                        <a class="text-muted" href="#!">Web Apps</a>
                    </p>
                    <p>
                        <a class="text-muted" href="#!">Mobile Apps</a>
                    </p>

                </div>

                <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

                    <h6 class="text-uppercase font-weight-bold">Contact</h6>
                    <hr class=" accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
                    <p>
                        <i class="mr-3"></i> New York, NY 10012, US</p>
                    <p>
                        <i class="mr-3"></i> info@example.com</p>
                    <p>
                        <i class="mr-3"></i> + 01 234 567 88</p>
                    <p>
                        <i class="mr-3"></i> + 01 234 567 89</p>

                </div>


            </div>

        </div>



        <div class="text-center text-black-50 py-3">© 2019 Copyright:
            <a class="text-muted" href="{% url 'blog:posts_list' %}"> Blogger.com</a>
        </div>
    </footer>
    <!-- Footer -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
</body>

</html>

templates/latest_posts.html
{% for post in latest_posts %} <div class="card">
    <div class="card-header">
        <span class="font-weight-bold">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </span>
        <span class="text-muted float-right">by &colon; {{ post.author }} |
            {{ post.created }}
        </span>
    </div>
</div>
<br>
{% empty %}
<p>No commented posts yet.</p>
{% endfor %}

templates/pagination.html
{% load blog_tags %}

<!-- <div class="col-lg-4 col-md-4 col-sm-4 col-xl-4" style="display: inline;">
    {% if page.has_previous %}
    <a class="btn btn-light btn-sm" href="?page=1">First &lt;&lt;</a> |
    <a class="btn btn-light btn-sm" href="?page={{ page.previous_page_number }}">Previous &lt;</a>
    {% endif %}
</div>

<div class="col-lg-4 col-md-4 col-sm-4 col-xl-4" style="display: inline;">
    <span class="btn">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
</div>


<div class="col-lg-4 col-md-4 col-sm-4 col-xl-4" style="display: inline;">
    {% if page.has_next %}
    <a class="btn btn-light btn-sm" href="?page={{ page.next_page_number }}">&gt; Next</a> |
    <a class="btn btn-light btn-sm" href="?page={{ page.paginator.num_pages }}">&gt;&gt; Last</a>
    {% endif %}
</div> -->


<ul class="pagination justify-content-center">
    {% if page.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page.previous_page_number }}">Previous</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
    </li>
    {% endif %}

    {% for page_number in 1|range:page.paginator.num_pages %}
    <li class="page-item"><a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a></li>
    {% endfor %}

    {% if page.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
    </li>
    {% endif %}
</ul>

templates/post_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}{{ post.title }}{% endblock title %}


{% block content %}
<br>
<div class="row">
    <div id="post_detail" class="col-lg-8">

        <div class="card">
            <div class="card-header">
                <div class="float-left">
                    <h3 style="padding: 15px 0px 0px 15px;">
                        <a style="text-decoration: none;"
                            href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
                    </h3>
                </div>
                <div class="text-muted float-right">
                    <table>
                        <tr>
                            <td>By</td>
                            <td>&colon; {{ post.author }}</td>
                        </tr>
                        <tr>
                            <td>Created</td>
                            <td>&colon; {{ post.created }}</td>
                        </tr>
                        <tr>
                            <td>Published</td>
                            <td>&colon; {{ post.publish }}</td>
                        </tr>
                        <tr>
                            <td>Last Updated</td>
                            <td>&colon; {{ post.created }}</td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="card-body" style="min-height: 200px">

                {% if post.tags.all.count > 0 %}
                <span class="text-muted">Tags:</span>
                {% for tag in post.tags.all %}

                <span style="display: inline;">
                    <a class="btn btn-sm btn-outline-dark"
                        href="{% url 'blog:posts_list_by_tag' tag.slug %}">{{ tag }}</a>
                </span>

                {% endfor %}
                {% else %}
                <span style="font-size: 14px; color: rgb(156, 156, 156);">No tags yet</span>
                {% endif %}
                <p class="align-middle">
                    <div class="card">
                        <div class="card-body">

                            {{ post.body }}
                        </div>
                    </div>
                </p>
            </div>
            <div class="card-footer">
                <h5 style="display: inline;">Comments</h5>
                <span class="text-muted">:
                    {% with comments.count as total_comments %}
                    {{ total_comments }} comment{{ total_comments|pluralize }}
                    {% endwith %}
                </span>
                <div style="background-color: white;padding: 15px 15px 15px 15px; border: 1px solid rgb(228, 228, 228)">
                    <table>

                        {% if comments %}

                        {% for comment in comments %}
                        <tr>
                            <td style="padding: 5px;">
                                <span class="text-muted" style="font-size: 11px;">
                                    {{ comment.created }}
                                </span>
                            </td>
                            <td style="padding: 5px;">
                                <span class="font-weight-bold" style="color: rgb(0, 153, 255); font-size: 18px;">
                                    {{ comment.name }}
                                </span>
                            </td>
                            <td>
                                <span style="font-size: 15px;">&colon; {{ comment.body }}</span>
                            </td>
                        </tr>
                        {% endfor %}

                        {% else %}
                        <tr>
                            <td>
                                <span style="font-size: 14px; color: rgb(156, 156, 156);"> No comments yet.
                                </span>
                            </td>
                        </tr>
                        {% endif %}

                    </table>
                </div>
                <div id=" addComment" style="padding: 15px">
                    <h5>Add Comment</h5>
                    {% if new_comment %}
                    <span style="border-color: transparent;">Your comment is added successfuly.</span>
                    {% endif %}
                    <hr>
                    <form action="." method="post" style="padding: 5px">
                        {% csrf_token %}
                        {{ comment_form|crispy }}
                        <input class="btn btn-outline-secondary btn-sm" type="submit" value="Add Comment">
                    </form>
                </div>
                <hr>
                <div>
                    <a class="btn btn-link btn-sm float-left" href="{% url 'blog:posts_list' %}">&lt;&lt; back to
                        blog</a>
                    <a class="btn btn-info btn-sm float-right" href="{% url 'blog:post_share' pk=post.id %}">Share</a>
                </div>
            </div>
        </div>

    </div>

    <div id="related_posts" class="col-lg-4" style="background-color: rgb(243, 242, 242);">
        <br>
        <h4>Related Posts</h4>
        <hr>
        {% for post in similar_posts %}
        <div class="card">
            <div class="card-header">
                <span class="font-weight-bold">
                    <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
                </span>
                <span class="text-muted float-right">by &colon; {{ post.author }} |
                    {{ post.created }}
                </span>
            </div>
        </div>
        <br>
        {% empty %}
        <p>No related posts.</p>
        {% endfor %}

    </div>
</div>
<br>
{% endblock content %}

templates/post_share.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Share Post{% endblock title %}


{% block content %}

<br>
<div class="row">
    <div class="col-1">

    </div>

    <div class="col-6">
        {% if sent %}
        <h2>Post Shared</h2>
        <hr>
        <p>Post "{{ post.title }}" was shared with "{{ form.cleaned_data.to }}" successfuly</p>
        <br>
        <a class="btn btn-link" href="{% url 'blog:post_detail' pk=post.id %}">&lt;&lt; Back to post</a>
        {% else %}
        <h2>Share Post</h2>
        <form action="." method="POST">{% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-success" type="submit" value="Send e-mail">
        </form>
        {% endif %}
    </div>

</div>

{% endblock content %}

templates/posts_list.html
{% extends 'base.html' %}
{% load blog_tags %}
{% block title %}Blogger{% endblock title %}


{% block searchform %}
<form class="form-inline my-2 my-lg-0" action="." method="POST">{% csrf_token %}
    <input class="form-control mr-sm-2" type="search" name="tag_slug" placeholder="Tag Slug" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
{% endblock searchform %}



{% block content %}

<br>
<div id="intro" class="row">
    <div class="col">

        <div>
            {% total_posts as total_posts%}
            <p>Hi, this is my blog, I've posted {{ total_posts }} post{{ total_posts|pluralize }} till now.</p>
        </div>
        {% if tag %}
        <h4 style="display: inline;"> search results:</h4>
        <button class="btn btn-outline-danger btn-sm" disabled>{{ tag.name }}</button>
        <hr>
        {% endif %}
    </div>
</div>

<div id="main" class="row">

    <div id="posts_list" class="col-lg-8">
        {% for post in posts %}
        <div class="card">
            <div class="card-header">
                <span class="font-weight-bold">
                    <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
                </span>
                <span class="text-muted float-right">by &colon; {{ post.author }} |
                    {{ post.created }}
                </span>
            </div>
            <div class="card-body" style="min-height: 100px">
                {% if post.tags.all.count > 0 %}
                <span class="text-muted">Tags:</span>
                {% for tag in post.tags.all %}

                <span style="display: inline;">
                    <a href="{% url 'blog:posts_list_by_tag' tag.slug %}"
                        class="btn btn-sm btn-outline-dark ">{{ tag }}</a>
                </span>

                {% endfor %}
                {% else %}
                <span style="font-size: 14px; color: rgb(156, 156, 156);">No tags yet</span>
                {% endif %}
                <p class="align-middle">
                    <div class="card">
                        <div class="card-body">

                            {{ post.body }}
                        </div>
                    </div>
                </p>
            </div>
            <div class="card-footer">
                <a class="btn btn-link btn-sm float-left" href="{% url 'blog:post_detail' pk=post.id %}">more
                    &gt;&gt;</a>
                <a class="btn btn-info btn-sm float-right" href="{% url 'blog:post_share' pk=post.id %}">Share</a>
            </div>
        </div>
        <br>
        {% endfor %}
    </div>


    <div id="latest_posts" class="col-lg-4" style="background-color: rgb(243, 242, 242);margin-bottom: 1.5em;">
        <div>
            <br>
            <h4>Latest Posts</h4>
            <hr>
            {% get_latest_posts 3 %}
        </div>

        <div>
            <br>
            <h4>Most Commented Posts</h4>
            <hr>
            {% get_most_commented_posts as most_commented_posts %}
            {% for post in most_commented_posts %}
            <div class="card">
                <div class="card-header">
                    <span class="font-weight-bold">
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </span>
                    <span class="text-muted float-right">by &colon; {{ post.author }} |
                        {{ post.created }}
                    </span>
                </div>
            </div>
            <br>
            {% empty %}
            <p>No commented posts yet.</p>
            {% endfor %}
        </div>
    </div>

</div>

<div id="pagination" class="col">
    {% include 'pagination.html' with page=posts %}
</div>

{% endblock content %}